# Generated by Django 3.0.6 on 2020-06-06 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='mail')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='nombre de usuario')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('plan', models.CharField(choices=[('free', 'free'), ('normal', 'normal'), ('premium', 'premium'), ('admin', 'admin')], default='free', max_length=8)),
                ('date_start_plan', models.DateField(blank=True, null=True)),
                ('time_pay', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='apellido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bookflix/static/autores', verbose_name='imagen')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='titulo')),
                ('description', models.TextField(blank=True, null=True)),
                ('mostrar_en_home', models.BooleanField(default=False)),
                ('video', models.URLField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=50, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portadas_libros')),
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('mostrar_en_home', models.BooleanField(default=False)),
                ('on_normal', models.BooleanField(default=False)),
                ('on_premium', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Author')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='BookByChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_chapter', models.IntegerField(default=1)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book')),
            ],
            options={
                'verbose_name': 'Libro por capítulo',
                'verbose_name_plural': 'Libro por capítulos',
            },
        ),
        migrations.CreateModel(
            name='ConfirmationMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('codigo', models.CharField(max_length=10)),
                ('tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active_now', models.BooleanField(default=False)),
                ('hour_activation', models.DateTimeField(blank=True, null=True)),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pleasures_author', models.ManyToManyField(blank=True, null=True, to='bookflix.Author')),
                ('pleasures_editorial', models.ManyToManyField(blank=True, null=True, to='bookflix.Editorial', verbose_name='Editoriales Favoritas')),
                ('pleasures_gender', models.ManyToManyField(blank=True, null=True, to='bookflix.Gender')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'unique_together': {('name', 'account')},
            },
        ),
        migrations.CreateModel(
            name='UserSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_solicitud', models.CharField(choices=[('1', 'alta'), ('2', 'cambio'), ('4', 'baja')], default='1', max_length=2)),
                ('type_of_plan', models.CharField(choices=[('f', 'free'), ('n', 'normal'), ('p', 'premium')], default='f', max_length=2)),
                ('date_of_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_limit_to_attend', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de usuario',
                'verbose_name_plural': 'Solicitudes de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='UpDatesBillboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_date', models.DateField(blank=True, null=True, verbose_name='actualizar')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Billboard')),
            ],
            options={
                'verbose_name': 'DarDeAltaNovedades',
                'verbose_name_plural': 'DarDeAltaNovedades',
            },
        ),
        migrations.CreateModel(
            name='UpDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_normal', models.DateField(blank=True, null=True, verbose_name='pasar a normal')),
                ('up_premium', models.DateField(blank=True, null=True, verbose_name='pasar a premium')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book')),
            ],
            options={
                'verbose_name': 'DarDeAltaLibro',
                'verbose_name_plural': 'DarDeAltaLibros',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False, verbose_name='me gusta')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Profile')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book')),
            ],
            options={
                'verbose_name': 'Me gusta',
                'verbose_name_plural': 'Me gusta/s',
            },
        ),
        migrations.CreateModel(
            name='ExpirationDatesBillboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Billboard')),
            ],
            options={
                'verbose_name': 'DarDeBajaNovdedad',
                'verbose_name_plural': 'DarDeBajaNovedades',
            },
        ),
        migrations.CreateModel(
            name='ExpirationDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_normal', models.DateField(blank=True, null=True, verbose_name='expiracion normal')),
                ('expiration_premium', models.DateField(blank=True, null=True, verbose_name='expiracion premium')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book')),
            ],
            options={
                'verbose_name': 'DarDeBajaLibro',
                'verbose_name_plural': 'DarDeBajaLibros',
            },
        ),
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('number', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='numero')),
                ('cod', models.IntegerField()),
                ('card_name', models.CharField(max_length=50, verbose_name='nombre de tarjeta')),
                ('date_expiration', models.DateField(verbose_name='fecha de vencimiento')),
                ('bank', models.CharField(max_length=50, verbose_name='banco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
            },
        ),
        migrations.CreateModel(
            name='CounterStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='fecha de inicio')),
                ('cant_reading', models.IntegerField(default=0, verbose_name='leyendo')),
                ('cant_future_read', models.IntegerField(default=0, verbose_name='en futuras lecturas')),
                ('cant_finished', models.IntegerField(default=0, verbose_name='terminados')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacion', to='bookflix.Book')),
            ],
            options={
                'verbose_name': 'Estadística de libro',
                'verbose_name_plural': 'Estadísticas de libros',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_a_spoiler', models.BooleanField(default=False, verbose_name='es espoiler')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Profile')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Editorial'),
        ),
        migrations.AddField(
            model_name='book',
            name='genders',
            field=models.ManyToManyField(to='bookflix.Gender'),
        ),
        migrations.CreateModel(
            name='StateOfBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('state', models.CharField(choices=[('reading', 'reading'), ('future_reading', 'future_reading'), ('finished', 'finished')], default='finished', max_length=16, verbose_name='estado')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Profile')),
            ],
            options={
                'verbose_name': 'Estado del libro',
                'verbose_name_plural': 'Estados del libro',
                'unique_together': {('book', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False, verbose_name='me gusta')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Profile')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Comment')),
            ],
            options={
                'verbose_name': 'Me gusta de comentario',
                'verbose_name_plural': 'Me gustas/s de comentarios',
                'unique_together': {('author', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='numero')),
                ('url', models.URLField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.BookByChapter')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'unique_together': {('number', 'book')},
            },
        ),
    ]
