# Generated by Django 3.0.6 on 2020-05-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='bookflix/static'),
        ),
    ]
