# Generated by Django 3.0.6 on 2020-06-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='confirmo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
