# Generated by Django 3.0.6 on 2020-05-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookflix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billboard',
            name='author',
        ),
        migrations.RemoveField(
            model_name='billboard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='billboard',
            name='video',
        ),
    ]
